# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -I../../lib/plumed/includelink 
PKG_PATH =  
PKG_LIB =   
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(plumed_SYSINC) 
PKG_SYSLIB =  $(plumed_SYSLIB) 
PKG_SYSPATH = $(plumed_SYSPATH) 
